import type { Metadata } from "next";
import Link from "next/link";
// // import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image'
import Avatar from '../../public/images/Untitled-2024-02-01-2251.excalidraw.svg';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const header = (
    <header>
      <div className="text-left py-4 my-4 ">
        {/* <Image src="/Untitled-2024-02-01-2251.excalidraw.svg" width={900} height={400}/> */}
        <Link href="/" className="flex ..."><h1 className="text-3xl font-bold text-slate-400 motion-safe:animate-pulse">@</h1><h1 className="text-3xl font-bold pb-2 hover:decoration-slate-400  underline underline-offset-4 decoration-slate-300">bakursky</h1></Link>
        <div className="p-4  bg-slate-200 rounded-md text-sm text-slate-700">
          <p>Привет мир! Меня зовут Ваня, а это архив моих постов. Пишу о жизни в целом и своих навязчивых интересах в частности :) Кринжово и с ошибками, но честно и с душой.</p>
          
            <ul className="mt-4">
            Принципы тегов:
              <li>🗿 выдал базу</li>
              <li>🥜 расколол мысленных орех</li>
              <li>🌱 вечнозеленая заметка (постоянно обновляется)</li>
              <li>🔥 поджог кому-то задницу</li>
              <li>📰 лонгрид</li>
            </ul>
          
        </div>
      </div>
    </header>
  )

  const footer = (
    <footer>
      <div className="mt-6 py-6 ">
        <p className="text-sm text-slate-700">Сбилженно с 💘 в Геленджике (C)</p>
      </div>
    </footer>
  )


  return (
    <html lang="en">
      <body className="bg-slate-100">
        <div className="mx-auto max-w-lg px-6 ">
          {header}
          {children}
          {footer}
        </div>
      </body>

    </html>
  );
}
